name: ci

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: '13 8 * * 0'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push - Debian [0.11.0]
        uses: docker/build-push-action@v5
        with:
          file: debian/slim/bookworm/0.11.0/Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bookworm-ziglang:0.11.0

      - name: Build and push - Debian [master]
        uses: docker/build-push-action@v5
        with:
          file: debian/slim/bookworm/master/Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bookworm-ziglang:latest

      - name: Build and push - Busybox [master]
        uses: docker/build-push-action@v5
        with:
          file: busybox/master/Dockerfile
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ziglang:latest
      
      - name: Build and push - Alpine [master]
        uses: docker/build-push-action@v5
        with:
          file: alpine/master/Dockerfile
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/alpine-ziglang:latest